### ISSUE TITLE
polymerize generate-wrapper does not generate all components in comps.yaml

### ISSUE THREAD

**Issue by ErikGrimes** [polymer-dart/polymerize_elements#3]
For example, iron_validatable_behavior.dart is no longer generated.  There are a total of 108 files currently in lib, but only 30 are now generated by polymerize v0.5.3.  I tried using build.sh as well as 
```
polymerize generate-wrapper --component-refs comps.yaml --dest-path out -p polymer_elements \
 --bower-needs-map Polymer.IronFormElementBehavior=package:polymer_elements/iron_form_element_behavior.dart \
 --bower-needs-map Polymer.Templatizer=package:polymer_element/polymer_element.dart \
 --bower-needs-map Templatizer=package:polymer_element/polymer_element.dart
```

**Comment by dam0vm3nt** [comment]
fixed missing external from `comps.yaml`, updated `polymer_element` to `0.5.3`.

I'm going to add some better error reporting to the generator in order to let the user know when it is failing and why.
